# Generated by Django 5.1.11 on 2026-08-17 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='الرابط')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('image', models.ImageField(upload_to='exhibitions/', verbose_name='الصورة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('current', 'حالي'), ('upcoming', 'قادم'), ('past', 'ماضي')], default='upcoming', max_length=20, verbose_name='الحالة')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('video_url', models.URLField(blank=True, verbose_name='رابط الفيديو')),
            ],
            options={
                'verbose_name': 'معرض',
                'verbose_name_plural': 'المعارض',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=40, verbose_name='الهاتف')),
                ('country', models.CharField(max_length=80, verbose_name='الدولة')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان العمل')),
                ('medium', models.CharField(max_length=120, verbose_name='الخامة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('image', models.ImageField(upload_to='requests/', verbose_name='صورة العمل')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
            ],
            options={
                'verbose_name': 'طلب عرض عمل',
                'verbose_name_plural': 'طلبات العرض',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exhibitions/gallery/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='التعليق')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='exhibitions.exhibition', verbose_name='المعرض')),
            ],
            options={
                'verbose_name': 'صورة معرض',
                'verbose_name_plural': 'صور المعارض',
            },
        ),
        migrations.CreateModel(
            name='ExhibitionProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('kind', models.CharField(choices=[('workshop', 'ورشة'), ('visit', 'زيارة'), ('talk', 'حديث'), ('show', 'عرض'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='النوع')),
                ('date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('place', models.CharField(blank=True, max_length=200, verbose_name='المكان')),
                ('short_text', models.TextField(blank=True, verbose_name='نبذة')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='exhibitions.exhibition', verbose_name='المعرض')),
            ],
            options={
                'verbose_name': 'فقرة البرنامج',
                'verbose_name_plural': 'برنامج المعرض',
                'ordering': ['date', 'pk'],
            },
        ),
    ]
