# Generated by Django 5.1.11 on 2026-08-17 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('country', models.CharField(blank=True, max_length=80, verbose_name='الدولة')),
                ('bio', models.TextField(blank=True, verbose_name='السيرة')),
                ('image', models.ImageField(blank=True, upload_to='artists/', verbose_name='الصورة')),
            ],
            options={
                'verbose_name': 'فنان',
                'verbose_name_plural': 'الفنانون',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='الرابط')),
                ('image', models.ImageField(upload_to='artworks/', verbose_name='الصورة')),
                ('year', models.CharField(blank=True, max_length=20, verbose_name='السنة')),
                ('medium', models.CharField(blank=True, max_length=120, verbose_name='الخامة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='works.artist', verbose_name='الفنان')),
                ('exhibition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='exhibitions.exhibition', verbose_name='المعرض')),
            ],
            options={
                'verbose_name': 'عمل فني',
                'verbose_name_plural': 'الأعمال الفنية',
                'ordering': ['-year', 'title'],
            },
        ),
    ]
