# Generated by Django 5.1.11 on 2026-08-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'رسالة اتصال',
                'verbose_name_plural': 'رسائل الاتصال',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Sun Boats', max_length=200, verbose_name='اسم الموقع')),
                ('tagline', models.CharField(blank=True, max_length=300, verbose_name='الشعار')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('logo', models.ImageField(blank=True, upload_to='site/', verbose_name='الشعار البصري')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='الهاتف')),
                ('whatsapp', models.CharField(blank=True, max_length=40, verbose_name='واتساب')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='العنوان')),
                ('facebook', models.URLField(blank=True, verbose_name='فيسبوك')),
                ('instagram', models.URLField(blank=True, verbose_name='إنستغرام')),
                ('hero_image', models.ImageField(blank=True, upload_to='site/', verbose_name='صورة الغلاف')),
            ],
            options={
                'verbose_name': 'الإعدادات',
                'verbose_name_plural': 'الإعدادات',
            },
        ),
    ]
