# Generated by Django 5.1.11 on 2026-08-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='youtube',
            field=models.URLField(blank=True, verbose_name='يوتيوب'),
        ),
    ]
